### ISSUE TITLE
Frontpage should not be in a variable, and definitely not contain css and js!

### ISSUE THREAD

**Issue by disassembler** [WhiteHouse/petitions#11]
https://github.com/WhiteHouse/petition/blob/7.x-1.x/modules/custom/wh_core/wh_core.install

The install hook calls all the update hooks. In the first update hook, your echo'ing all your css, html, and js of the frontpage into a variable. This really, really, really bad practice...

**Comment by bryanhirsch** [comment]
@disassembler Thanks for your attention to this issue. I believe this was resolved with the addition of the petitions_homepage in 7.x-1.0-alpha26.
