### ISSUE TITLE
Cannot receive verfication emails since 2019-08-24 22:51:01 (UTC)

### ISSUE THREAD

**Issue by alexvong243f** [WhiteHouse/petitions#142]
Dear devs,

It is reported that crackers has prevented people from signing petitions by flooding the service (DDoS) since 2019-08-24 22:51:01 (UTC) .

If this is indeed the case, please consider adding additional time to petitions with completion date later than 2019-08-24 22:51:01 (UTC).

**References**
https://twitter.com/newworldstimes/status/1165661357980684288
https://twitter.com/nikiv_86911/status/1165476411097747456

**Comment by alexvong1995** [comment]
Please see this twitter thread for more details: https://twitter.com/newworldstimes/status/1165661357980684288
