### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by diaspar** [WhiteHouse/petitions#40]
Form some reason the step 5 is not working as expected for me:

5) Follow the normal Drupal installation process. When prompted to select a profile, select "Petitions". Drupal will rewrite your settings.php file. After it does, you will be prompted to add a snippet like this to the end of settings.php. Do this before you visit your site, otherwise Drupal will be unhappy:

I did not find a step on the web installer where its prompts me to add the mongo config lines. I arrived to the normal db selection and mongo is not one of the options. I assume I dont have to seup anything here because mysql and other wont be needed.

Yes, when a profile was asked on the instatter (first one) I did choose petitions.

Please tell me what I am doing wrong.

**Comment by lunatic0** [comment]
This project uses both mysql and mongodb.

You should continue the installation normaly. After the installation and before visiting your site you have to edit the settings.php and add at the end of the file the congifuration lines for mongodb.
