### ISSUE TITLE
missing petition_install modules - step 6

### ISSUE THREAD

**Issue by lunatic0** [WhiteHouse/petitions#41]
the modules mentioned in step seem to be missing

$drush en -y petition_install1
petition_install1 was not found and will not be enabled.             [warning]
There were no extensions that could be enabled.                      [ok]

$ drush en -y petition_install2
petition_install2 was not found and will not be enabled.             [warning]
There were no extensions that could be enabled.                      [ok]

$ drush en -y petition_install3
petition_install3 was not found and will not be enabled.             [warning]
There were no extensions that could be enabled.                      [ok]

$ drush en -y petition_install4
petition_install4 was not found and will not be enabled.             [warning]
There were no extensions that could be enabled.                      [ok]

step 7 (if there is any) is also missing from the installation instructions

**Comment by bryanhirsch** [comment]
commit caa261b8258b26fe74f675cab36407fbd9666125
Author: Bryan Hirsch bryan_s_hirsch@oa.eop.gov
Date:   Tue Aug 28 19:15:26 2012 -0400

```
Add petition_install helper modules referenced in install instructions.

Resolves issue #40 in GitHub issue queue:
https://github.com/WhiteHouse/petition/issues/40
```
