### ISSUE TITLE
Sorry, the profile you have chosen cannot be loaded. 

### ISSUE THREAD

**Issue by evnngsky** [WhiteHouse/petitions#42]
At Step 5,
After select profile 'petition' and select language,
installer shows only message 'Sorry, the profile you have chosen cannot be loaded.' without progress.

Surely, 1,2,3,4 steps went well, and I checked 'phpinfo' for mongodb and mysql extentions.

**Comment by bryanhirsch** [comment]
Fixed, see https://github.com/WhiteHouse/petition/issues/40#commits-ref-caa261b.

commit caa261b8258b26fe74f675cab36407fbd9666125
Author: Bryan Hirsch bryan_s_hirsch@oa.eop.gov
Date:   Tue Aug 28 19:15:26 2012 -0400

```
Add petition_install helper modules referenced in install instructions.

Resolves issue #40 in GitHub issue queue:
https://github.com/WhiteHouse/petition/issues/40
```

**Comment by jasonblanchard** [comment]
See issue here on Drupal.org: http://drupal.org/node/1075012#comment-6051720

Renaming the profile directory to "petitions" instead of "petition" fixed it for me.

**Comment by benkorlems** [comment]
After renaming to 'petitions' the following error message comes up

Required modules not found.
The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as sites/all/modules. Missing modules: Captcha, Context, Date, Entity, Entitycache, Entityreference, Features, Globalredirect, Imce, Libraries, Pathauto, Petitionssignatureform, Rest_server, Services, Services_documentation, Shunt, Textcaptcha, Wysiwyg
