### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mbelinsky** [WhiteHouse/petitions#50]
Are you planning on having any localization features and functionality for Spanish and other languages? 

If so, will you have an XML for easy translation or will you be using any services to crowdsource this functionality?

**Comment by bryanhirsch** [comment]
Localization is not currently on [the roadmap](https://github.com/WhiteHouse/petitions/blob/7.x-2.x/README.md). Right now we're working on the API. The first public release will be out soon.

But please don't let the fact that we're not focused on this right now discourage you if you're working on localization for your own instance of the petitions distro. Something like this would be a great contribution to the project.

If you're working on this yourself and you'd like to collaborate on getting something like this into the code base, let's move this conversation over to the drupal.org issue queue [here](http://drupal.org/project/issues/petitions) and see if we can find some ways to collaborate.
