### ISSUE TITLE
Signatures for the 28th not showing up

### ISSUE THREAD

**Issue by chris3991m** [WhiteHouse/petitions#93]
https://petitions.whitehouse.gov/petition/allow-trans-people-military/FbFBNrbc

This is one example.  I thought signatures were supposed to continuously show up?  I tried signing but it didn't show.

**Comment by TravisCarden** [comment]
Thank you for the report, @chris3991m. Signature processing got backed up over the weekend, but it's restored to normal and all signatures have been counted. Your example petition has been incremented. Thanks!
